version: "3.8"

services:
  docusaurus-wrangles-io:
    image: ghcr.io/wrangleworks/docusaurus:latest
    container_name: docusaurus-wrangles-io
    restart: unless-stopped
    ports:
      - "3007:80" # host:container (change 3003 if it conflicts)
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "1.0"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s
    networks:
      - docusaurus-proxy

networks:
  docusaurus-proxy:
    external: true
